#!/usr/bin/python
#encoding=utf-8
import random
import webbrowser
import time
import os

quest_num = 20
add_max = 100
op_max = 90
pass_score = 90
pass_time = 15

start_time = time.time()
score = 0
for i in range(1,quest_num+1):
    oper = random.randint(0,1)
    # A + B = C
    if op_max > 0:
        while True:
            A = random.randint(1, op_max)
            B = random.randint(1, op_max)
            C = A + B
            if add_max>0:
                if C<=add_max: break
            else:
                break
    elif add_max > 0:
        C = random.randint(1, add_max)
        A = random.randint(1, C)
        B = C - A
    else:
        C = random.randint(1, 100)
        A = random.randint(1, C)
        B = C - A
    if oper==0:
        oper_char = '+'
        a = A
        b = B
    else:
        oper_char = '-'
        a = C
        b = A
    trynum = 1
    per_start_time = time.time()
    while True:
        calc_str = "(%0d):  %0d %s %0d = "%(i,a,oper_char,b)
        print(calc_str),
        c = raw_input('')
        try:
            c = int(c)
        except ValueError:
            continue
        result = False
        if (oper == 0 and (a+b==c)):
            result = True
        elif (oper == 1 and (a-b==c)):
            result = True
        else:
            result = False
        if result:
            print ' ✅'
            if trynum == 1: score = score+1
            break
        else:
            print ' ❌'
        trynum = trynum + 1
    per_end_time = time.time()
    per_total_time = int(per_end_time-per_start_time)
    if per_total_time <= 15:
        print '这道题用了 %0d 秒, 很棒哦❤️ ' % (per_total_time)
    elif per_total_time <= 30:
        print '这道题用了 %0d 秒, 加油哦💛' % (per_total_time)
    else:
        print '这道题用了 %0d 秒, 太慢咯, 要认真一些哦💔' % (per_total_time)

score = int(score *100 / quest_num)
print '你得了 %0d 分'%score

end_time = time.time()
total_time = int(end_time-start_time)
avg_time = int(total_time/quest_num)
print '你一共花了 %0d 秒, 平均一题用了 %0d 秒' % (total_time, avg_time)

if score > pass_score and avg_time <= pass_time:
    for file in os.listdir('/Users/lsxld/Documents/passwd'):
        print('iPad 密码是'+file)
else:
    print('没有达到要求哦，还不能告诉你密码，继续努力吧!')
