--- #YAML:1.0
name:               Tkx
version:            1.07
abstract:           Yet another Tk interface
author:
    - Gisle Aas <gisle@activestate.com>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
requires:
    perl:  5.008
    Tcl:   0.81
resources:
    MailingList:  mailto:tcltk@perl.org
    repository:   http://github.com/gisle/tkx/
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.4801
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
