require(KEGG.db)
kegg=as.list(KEGGPATHID2NAME)
require(GO.db)
as.list(GOTERM)->go
go2probe=as.list(illuminaMousev2GO2PROBE)
as.list(illuminaMousev2PATH2PROBE)->kegg2probe
######################FunctionEnrichment###################
FunctionEnrichment=function(Namedpvalues,functionList,cutPvalue,Name=NULL)
{
Allgenes=names(Namedpvalues)
NumAll=length(Allgenes)
Siggenes=Allgenes[Namedpvalues<=cutPvalue]
NumSig=length(Siggenes)
lapply(functionList,FUN=function(x,Allgenes,Siggenes){
NumAllinPath=sum(Allgenes %in% x)
NumSiginPath=sum(Siggenes %in% x)
mat=matrix(c(NumSiginPath,NumAllinPath-NumSiginPath,NumSig-NumSiginPath,
NumAll-NumSig-NumAllinPath+NumSiginPath),nrow=2)
fisher.test(mat,alternative="greater")$p.value->pval
return(c(length(x),NumAllinPath,NumSiginPath,pval))
},Allgenes=Allgenes,Siggenes=Siggenes)->tab
do.call(rbind,tab)->tab
colnames(tab)=c("Total","GenesWithIn","SigGenesWithIn","PValue")
tab=tab[order(tab[,4]),]
if(!is.null(Name))
{
as.data.frame(tab)->tab
tab$Name=unlist(Name[rownames(tab)])
return(tab)
}
return(tab)
}
###################Barplot######################
func.barplot=function(FuncEnrich,pval.cut=0.01,...)   #dataframe generated by FunctionEnrichment function
{
par(mar=c(2,15,2,2))
FuncEnrich=FuncEnrich[FuncEnrich$PValue<=pval.cut,]
FuncEnrich=FuncEnrich[order(FuncEnrich$PValue,decreasing=T),]
draw=t(matrix(c(FuncEnrich$SigGenesWithIn,FuncEnrich$GenesWithIn-FuncEnrich$SigGenesWithIn),ncol=2))
pos=barplot(draw,names.arg=FuncEnrich$Name,horiz=T,las=1,xlim=c(0,max(FuncEnrich$GenesWithIn)*1.2),...)
text(x=FuncEnrich$GenesWithIn,y=pos,labels=paste(FuncEnrich$SigGenesWithIn,"/",
FuncEnrich$GenesWithIn,sep=""),adj=-0.1,cex=0.7)
}
##################GetGenes#####################
as.list(illuminaMousev2SYMBOL)->probe2symbol
EnrichedGeneList=function(SigGeneNames,SelFunListID,functionList)
{
SelectList=functionList[SelFunListID]
lapply(SelectList,FUN=function(x,SigGeneNames){
res=x[x %in% SigGeneNames]
names(res)=unlist(probe2symbol[res])
return(res)
},SigGeneNames=SigGeneNames)
}
GeneList2Dataframe=function(EnrichedGeneList)
{
names(EnrichedGeneList)->genename
rep(genename,times=sapply(EnrichedGeneList,length))->allid
unlist(sapply(EnrichedGeneList,FUN=names))->allsymbol
unlist(EnrichedGeneList,use.names=F)->allprobe
data.frame(ID=allid,Probe=allprobe,GeneSymbol=allsymbol)
}

#####################Build Sigene List#####################
names(as.list(illuminaMousev2ACCNUM))->allprobe
read.table("c:/tmp/sigene.txt",sep="\t",head=F,stringsAsFactors=F)->data
pval=rep(1,length(allprobe)) 
names(pval)=allprobe
pval[data[[1]]]=data[[3]]
######################Kegg Enrich####################
FunctionEnrichment(pval,kegg2probe,0.05,Name=kegg)->keggEnrich
EnrichedGeneList(data[[1]],rownames(keggEnrich)[keggEnrich$PValue<0.01],kegg2probe)->KeggEnrichedGenes
GeneList2Dataframe(KeggEnrichedGenes)->KeggEnrichedGenes
func.barplot(keggEnrich,pval.cut=1e-2,cex.names=0.7,space=0.5)
#####################Go Enrich######################
FunctionEnrichment(pval,go2probe,0.05)->goEnrich
as.data.frame(goEnrich)->goEnrich
goEnrich$Ontology=unlist(lapply(go[rownames(goEnrich)],Ontology))
goEnrich$Name=unlist(lapply(go[rownames(goEnrich)],Term))
func.barplot(goEnrich[goEnrich$Ontology=="BP",],pval.cut=1e-4,cex.names=0.7,space=0.5,main="Biology Process")
func.barplot(goEnrich[goEnrich$Ontology=="MF",],pval.cut=1e-4,cex.names=0.7,space=0.5,main="Molecular Function")
func.barplot(goEnrich[goEnrich$Ontology=="CC",],pval.cut=1e-4,cex.names=0.7,space=0.5,main="Cellular Component ")
EnrichedGeneList(data[[1]],rownames(goEnrich)[goEnrich$PValue<0.01],go2probe)->GOEnrichedGenes
GeneList2Dataframe(GOEnrichedGenes)->GOEnrichedGenes
######################OutPut ###########################
write.csv(KeggEnrichedGenes,"Probe2KEGG.csv",row.names=F)
write.csv(GOEnrichedGenes,"Probe2GO.csv",row.names=F)
write.csv(keggEnrich,"KeggEnrich.csv")
write.csv(goEnrich,"GOEnrich.csv")